### ISSUE TITLE
"update cannot be installed"

### ISSUE THREAD

**Issue by NetNinja** [tutumcloud/tutum-docker-wordpress-nosql#14]
I'm getting an error message in my Tutum Wordpress install and was told my tutum.com support to report the issue here. The error message states when trying to update Wordpress: 
"The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions.: wp-admin/includes/update-core.php Installation Failed." I think I know the solution it just involves adjusting file permissions inside the /wp-admin folder et al. What's the best way to adjust/change file permissions inside a Tutum/Docker/Wordpress install?
Thanks

**Comment by tifayuki** [comment]
If you want to modify file permissions, you can add the code at the top of `run.sh` add rebuild the image again.
