### ISSUE TITLE
Infinite loop on restart

### ISSUE THREAD

**Issue by Ramblurr** [tutumcloud/tutum-docker-wordpress-nosql#17]
If you look at [run.sh:24](https://github.com/tutumcloud/tutum-docker-wordpress-nosql/blob/master/run.sh#L24), the run script will exec *itself* when `/.mysql_db_created` exists.

This results in an infinite loop!

Shouldn't the `exit 1` be replaced with the commands to start apache?

**Comment by tifayuki** [comment]
Oh yes, you are right.

the old `run.sh` is in the base image, whose content is 
```
source /etc/apache2/envvars
exec apache2 -D FOREGROUND
```

I renamed `run-wordpress.sh` to `run.sh`, causing the issue.

I will fix it soon.

Thank you so much.
